syntax enable
set hidden
set nowrap
set mouse=a
set relativenumber
set number
set termguicolors
set noswapfile
set clipboard+=unnamedplus
set nowrap                              
set encoding=utf-8                     
set fileencoding=utf-8
set ruler
set tabstop=2
set shiftwidth=2
set smarttab	
set expandtab	
set cursorline
set showtabline=2
set nobackup
set nowritebackup
set updatetime=100
set formatoptions-=cro
set timeoutlen=500
